var TopLevel = {
"app" : function () {},
"BrowserWindow" : function () {},
"close" : function () {},
"console" : function () {},
"crashReporter" : function () {},
"getItem" : function () {},
"JSON" : function () {},
"loadURL" : function () {},
"local-storage" : function () {},
"LocalStorage" : function () {},
"log" : function () {},
"on" : function () {},
"parse" : function () {},
"platform" : function () {},
"quit" : function () {},
"resolve" : function () {},
"setItem" : function () {},
"start" : function () {},
"stringify" : function () {},
"then" : function () {},
"type" : function () {}
}